Create a 1D array of numbers from 0 to 9

In [34]:
import numpy

arr = numpy.array([0,1,2,3,4,5,6,7,8,9])

print(arr)

[0 1 2 3 4 5 6 7 8 9]


Create a 2D array with shape (3, 3), where values range from 1 to 9.


In [19]:
import numpy as np

arr2 = np.array([[1,2,3,4,5,6,7,8,9], [1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])

print(arr2)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


Create a 3D array of shape (2, 3, 4) filled with random integers from 1 to 100.

In [31]:
import numpy as np

arr3 = np.array([[[1, 2,0], [2,1,0], [4,3,0]],
 [[1,2,3], [4,3,2], [3,3,3]],
 [[4,3,2], [1,2,3], [4,4,4]]])

print(arr3)

[[[1 2 0]
  [2 1 0]
  [4 3 0]]

 [[1 2 3]
  [4 3 2]
  [3 3 3]]

 [[4 3 2]
  [1 2 3]
  [4 4 4]]]


Given the array arr2 from Task 1, extract the second row.


In [28]:
second_row = arr2[1]
print(second_row)

[1 2 3 4 5 6 7 8 9]


Extract the element at the 3rd row and 2nd column of arr2.

In [29]:


element = arr2[2, 1]
print(element)


2


Extract all elements from the 3D array arr3 at the first index (0th layer)

In [32]:
firstIndex=arr3[0]
print(firstIndex)

[[1 2 0]
 [2 1 0]
 [4 3 0]]


Reshape the 1D array from Task 1 into a 2x5 2D array

In [35]:
# prompt: Reshape the 1D array from Task 1 into a 2x5 2D array

reshaped_arr = arr(2, 5)
print(reshaped_arr)


TypeError: 'numpy.ndarray' object is not callable